module.exports = {
  apps: [
    {
      name: 'ege',
      cwd: __dirname,
      script: './server/index.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      time: true,
      env: {
        NODE_ENV: 'production',
        PORT: '5175',
        APP_ALLOWED_ORIGINS: 'http://localhost,capacitor://localhost,ionic://localhost',
        AUTH_COOKIE_SAME_SITE: 'None',
        AUTH_COOKIE_SECURE: 'true',
        PLATFORM_DATA_DIR: '/root/platform-data',
        PLATFORM_UPLOADS_DIR: '/root/platform-uploads',
        PLATFORM_COLLAB_DIR: '/root/platform-collab',
        LEARNING_GROUPS_ENABLED: '1',
        LEARNING_GROUP_RTC_ENABLED: '0',
        COLLAB_PERSISTENCE: '1',
        BOARD_COLLAB_SNAPSHOT_PERSISTENCE: '1',
        BOARD_COLLAB_SNAPSHOT_WRITE_DEBOUNCE_MS: '60000',
        AUTH_SESSION_PERSIST_MIN_EXTENSION_MS: '900000',
        PYTHON_RUN_TIMEOUT_MS: '3000',
        PYTHON_RUN_TOTAL_TIMEOUT_MS: '8000',
        PYTHON_RUN_MAX_CONCURRENT: '1',
        PYTHON_RUN_MAX_QUEUE: '6',
        PYTHON_RUN_RATE_LIMIT: '6',
        PYTHON_RUN_RATE_WINDOW_MS: '60000',
      },
    },
  ],
};
