import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync, spawn } from 'node:child_process';
import { PythonEditMedia } from './python-edit-media.mjs';
const ffmpeg = process.env.FFMPEG_PATH || (process.platform === 'win32' ? 'C:/ProgramData/chocolatey/bin/ffmpeg.exe' : 'ffmpeg');
let available = true; try { execFileSync(ffmpeg, ['-version'], { windowsHide: true, stdio: 'ignore' }); } catch { available = false; }
const run = args => execFileSync(ffmpeg, ['-hide_banner','-loglevel','error', ...args], { windowsHide: true, maxBuffer: 10 * 1024 * 1024 });
test('preview reads already written frames from an unfinished MKV without stopping its writer', {timeout:30000,skip:!available&&'ffmpeg unavailable'}, async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ivan100-open-mkv-'));
  const id=crypto.randomUUID(),file=path.join(root,`lesson-${id}.mkv`);
  const child=spawn(ffmpeg,['-hide_banner','-loglevel','error','-y','-re','-f','lavfi','-i','testsrc2=s=320x180:r=30:d=60','-c:v','libx264','-preset','ultrafast','-g','30',file],{windowsHide:true,stdio:['pipe','ignore','pipe']});
  let errors='';child.stderr.on('data',chunk=>errors+=chunk);
  t.after(async()=>{if(child.exitCode===null){const done=new Promise(resolve=>child.once('exit',resolve));child.stdin.write('q\n');await Promise.race([done,new Promise(resolve=>setTimeout(resolve,2000))]);if(child.exitCode===null)child.kill();}fs.rmSync(root,{recursive:true,force:true});});
  await new Promise(resolve=>setTimeout(resolve,6500));
  assert.equal(child.exitCode,null,errors);
  const media=new PythonEditMedia({ffmpeg,root:path.join(root,'cache')});
  const job={id,file,pythonTimeline:{revision:1,sourceEnd:6,clips:[{start:0,end:2}]}};
  const previewId=await media.preview(job,job.pythonTimeline.clips,root);
  assert.ok(fs.statSync(media.previews.get(previewId).file).size>1000);
  assert.equal(child.exitCode,null,'Reading preview never stops the source writer');
});
test('actual ffmpeg montage keeps exact colored frames, audio and original source after cuts/reorder', { timeout: 60000, skip: !available && 'ffmpeg unavailable' }, async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan100-edit-media-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const id = crypto.randomUUID(), file = path.join(root, `lesson-${id}.mkv`);
  run(['-y','-f','lavfi','-i','color=red:s=320x180:r=30:d=1','-f','lavfi','-i','color=blue:s=320x180:r=30:d=1','-f','lavfi','-i','color=lime:s=320x180:r=30:d=1',
    '-f','lavfi','-i','sine=frequency=440:sample_rate=48000:duration=1','-f','lavfi','-i','sine=frequency=880:sample_rate=48000:duration=1','-f','lavfi','-i','sine=frequency=1320:sample_rate=48000:duration=1',
    '-filter_complex','[0:v][1:v][2:v]concat=n=3:v=1:a=0[v];[3:a][4:a][5:a]concat=n=3:v=0:a=1[a]', '-map','[v]','-map','[a]', '-c:v','libx264','-g','90','-c:a','aac',file]);
  const before = crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
  const media = new PythonEditMedia({ ffmpeg, root: path.join(root, 'cache') });
  const job = { id, file, pythonTimeline: { revision: 3, sourceEnd: 3, clips: [{start:2.2,end:2.8},{start:.7,end:1.3}] } };
  assert.ok(Math.abs(await media.duration(job,root)-3)<.1);
  const output = path.join(root,'edited.mp4');
  await media.exclusive(job,()=>media.render(job,job.pythonTimeline.clips,root,output));
  const probe = JSON.parse(execFileSync(ffmpeg.replace(/ffmpeg(\.exe)?$/,'ffprobe$1'), ['-v','error','-show_entries','format=duration:stream=codec_type','-of','json',output], { windowsHide:true }));
  assert.ok(Math.abs(Number(probe.format.duration)-1.2)<.15, probe.format.duration);
  assert.deepEqual(probe.streams.map(stream=>stream.codec_type),['video','audio']);
  const pixel = at => [...run(['-ss',String(at),'-i',output,'-frames:v','1','-vf','scale=1:1','-f','rawvideo','-pix_fmt','rgb24','pipe:1'])];
  const green=pixel(.2),red=pixel(.75),blue=pixel(1.05);
  assert.ok(green[1]>150 && green[0]<50 && green[2]<50,green);
  assert.ok(red[0]>150 && red[1]<50 && red[2]<50,red);
  assert.ok(blue[2]>150 && blue[0]<50 && blue[1]<50,blue);
  const audio=run(['-i',output,'-vn','-f','s16le','-ac','1','pipe:1']);
  assert.ok(audio.length>100000); assert.ok(audio.some(value=>value>0));
  const frequency=at=>{const first=Math.floor(at*48000),last=first+4800;let changes=0;for(let i=first+1;i<last;i++)if((audio.readInt16LE(i*2)>=0)!==(audio.readInt16LE((i-1)*2)>=0))changes++;return changes/2/.1;};
  assert.ok(Math.abs(frequency(.15)-1320)<40,'Green video has green source audio');
  assert.ok(Math.abs(frequency(.75)-440)<40,'Red video has red source audio');
  assert.ok(Math.abs(frequency(1.03)-880)<40,'Blue video has blue source audio');
  const previewId=await media.preview(job,[job.pythonTimeline.clips[1]],root);
  assert.ok(fs.existsSync(media.previews.get(previewId).file)); assert.equal(media.work,null);
  assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),before);
  const busy=media.exclusive(job,async()=>{await new Promise(resolve=>setTimeout(resolve,100));});
  await assert.rejects(media.exclusive(job,async()=>{}),/Дождитесь/); await busy;
  await assert.rejects(media.render(job,[{start:-1,end:1}],root,path.join(root,'bad.mp4')),/границы/);
  assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),before);
});
