import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {participationDay,participationOccurrence} from '../src/utils/groupParticipation.js';

test('individual group plans control schedule, debt, feedback and attendance while a required absence remains chargeable', {timeout:45000}, async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'group-participation-'));
  const data=path.join(root,'data');fs.mkdirSync(data);
  const write=(name,value)=>fs.writeFileSync(path.join(data,name+'.json'),JSON.stringify(value));
  const now=Date.now(),before=new Date(now-40*86400000).toISOString();
  const occurrence=offset=>`${participationDay(now+offset*86400000)}T20:00:00+03:00`;
  write('teachers',[{id:'t',code:'teacher',name:'Teacher',createdAt:before}]);
  write('students',['a','b'].map(id=>({id,teacherId:'t',code:id,name:id,grade:'11',studyStatus:'active',createdAt:before})));
  write('tests',{});write('mock-exams',[]);write('progress',Object.fromEntries(['a','b'].map(id=>[id,{schedule:[],homeworks:[],mockAttempts:{}}])));
  write('learning-groups',[{id:'g',teacherId:'t',name:'Группа',status:'active',startedAt:before,createdAt:before,pricePerLesson:1000,members:['a','b'].map(studentId=>({studentId,status:'active',joinedAt:before}))}]);
  const lessons=[['past-required',-5],['past-other',-3],['future-required',2],['future-other',4]].map(([id,offset])=>({id,groupId:'g',teacherId:'t',participantIds:['a','b'],startAt:occurrence(offset),durationMinutes:60,topic:id,source:'availability-plan',scheduleEntryId:'seed:'+id,status:offset<0?'completed':'scheduled',createdAt:before,updatedAt:before,...(offset<0?{completedAt:occurrence(offset)}:{})}));
  write('learning-lesson-sessions',lessons);
  write('learning-attendance',['past-required','past-other'].map(sessionId=>({sessionId,groupId:'g',teacherId:'t',studentId:'a',status:'absent',presentSeconds:0})));
  const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
  const child=spawn(process.execPath,['server/index.js'],{cwd:path.resolve('.'),env:{...process.env,PORT:String(port),NODE_ENV:'test',TZ:'Europe/Moscow',PLATFORM_CALENDAR_TIME_ZONE:'Europe/Moscow',PLATFORM_DATA_DIR:data,PLATFORM_UPLOADS_DIR:path.join(root,'uploads'),PLATFORM_JSON_BACKUPS_DIR:path.join(root,'backups'),COLLAB_PERSISTENCE:'0',DISABLE_STARTUP_XP_REBALANCE:'1',LEARNING_GROUPS_ENABLED:'1',LEARNING_GROUP_RTC_ENABLED:'0'},stdio:['ignore','pipe','pipe']});
  let logs='';child.stdout.on('data',c=>{logs+=c;});child.stderr.on('data',c=>{logs+=c;});
  t.after(async()=>{if(child.exitCode===null){child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),new Promise(r=>setTimeout(r,2500))]);if(child.exitCode===null)child.kill('SIGKILL');}fs.rmSync(root,{recursive:true,force:true});});
  const base=`http://127.0.0.1:${port}`;
  for(let i=0;;i++){try{if((await fetch(base+'/api/client-build-version')).ok)break;}catch{/* The isolated server is still starting. */}if(i>150||child.exitCode!==null)throw Error(logs);await new Promise(r=>setTimeout(r,100));}
  const call=async(route,token,body,method='GET',status=200)=>{const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json();assert.equal(r.status,status,`${route}: ${JSON.stringify(j)}`);return j;};
  const teacher=(await call('/api/login',null,{code:'teacher'},'POST')).token;
  const a=(await call('/api/login',null,{code:'a'},'POST')).token;
  const b=(await call('/api/login',null,{code:'b'},'POST')).token;
  const planRoute='/api/learning-groups/g/members/a/participation';
  const slots=[participationOccurrence(lessons[2]).slot];
  await call(planRoute,a,{mode:'all'},'PUT',403);
  await call(planRoute,teacher,{from:participationDay(now-86400000),mode:'all'},'PUT',400);
  await call(planRoute,teacher,{from:'2026-02-31',mode:'all'},'PUT',400);
  await call(planRoute,teacher,{from:participationDay(now),mode:'selected',slots:[]},'PUT',400);
  await call(planRoute,teacher,{from:participationDay(now),mode:'selected',slots},'PUT');
  const schedule=await call('/api/student-schedule',a);
  const rows=schedule;
  const payment = row => row.payment.statesByDate[row.date];
  assert.ok(rows.some(e=>e.lessonId==='future-required'));
  assert.ok(!rows.some(e=>e.lessonId==='future-other'));
  assert.equal(payment(rows.find(e=>e.lessonId==='past-required')).status,'unpaid','Missing a mandatory lesson does not cancel its price');
  assert.ok((await call('/api/student-schedule',b)).some(e=>e.lessonId==='future-other'),'Other students retain the full schedule');
  const review=await call(planRoute+'/review',teacher,{mode:'selected',slots},'POST');
  assert.deepEqual(review.lessons.map(l=>l.id),['past-other']);
  const exception=id=>`/api/learning-groups/g/lessons/${id}/participation`;
  const financeRoute='/api/teacher-finance?month='+participationDay(lessons[1].startAt).slice(0,7);
  const ledger=()=>JSON.parse(fs.readFileSync(path.join(data,'teacher-finances.json'),'utf8')).t.lessonLedger;
  await call(financeRoute,teacher);
  const otherDay=participationDay(lessons[1].startAt);
  const wasRecorded=Object.values(ledger()).some(row=>row.studentId==='a'&&row.dayKey===otherDay);
  assert.equal(wasRecorded,true,'Finance has already persisted the historical unpaid lesson');
  await call(exception('past-other'),teacher,{studentId:'a',assigned:false},'PUT');
  await call(financeRoute,teacher);
  assert.equal(Object.values(ledger()).some(row=>row.studentId==='a'&&row.dayKey===otherDay),false,'Explicit correction removes an old unpaid finance snapshot');
  assert.ok(Object.values(ledger()).some(row=>row.studentId==='a'&&row.dayKey===participationDay(lessons[0].startAt)&&!row.paid),'The mandatory missed lesson remains in finance');
  const corrected=await call('/api/student-schedule',a);
  assert.ok(!corrected.some(e=>e.lessonId==='past-other'));
  assert.equal(payment(corrected.find(e=>e.lessonId==='past-required')).status,'unpaid');
  assert.equal((await call('/api/learning-lesson-feedback/pending',a)).lesson.id,'past-required');
  const attendance=await call('/api/learning-groups/g/lessons/past-other/attendance',teacher);
  assert.equal(attendance.records.find(r=>r.studentId==='a').participationRequired,false);
  const progress=(await call('/api/learning-groups/g/progress',a)).progress;
  assert.equal(progress.self.attendance.absent,1,'The excluded lesson no longer counts as an absence');
  const paidKey=payment(corrected.find(e=>e.lessonId==='future-required')).paidMarkKey;
  await call('/api/teacher-calendar-marks',teacher,{teacherId:'t',set:{[paidKey]:new Date().toISOString()}},'PATCH');
  await call(exception('future-required'),teacher,{studentId:'a',assigned:false},'PUT',409);
  const paid=(await call('/api/student-schedule',a)).find(e=>e.lessonId==='future-required');
  assert.equal(payment(paid).status,'paid');
  await call(planRoute,teacher,{from:participationDay(now),mode:'selected',slots:[participationOccurrence(lessons[3]).slot]},'PUT');
  const prepaidExcluded=(await call('/api/student-schedule',a)).find(e=>e.lessonId==='future-required');
  assert.ok(prepaidExcluded,'An already prepaid occurrence remains visible even when the future plan changes');
  assert.equal(payment(prepaidExcluded).status,'paid');
  await call(planRoute,teacher,{from:participationDay(now),mode:'all',slots:[]},'PUT');
  assert.ok((await call('/api/student-schedule',a)).some(e=>e.lessonId==='future-other'));
  assert.equal(fs.readFileSync(path.join(data,'learning-groups.json'),'utf8').includes('participationPlans'),true);
});
