import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createGuestMeetingStore, parseMeetingRoomId, meetingRoomId } from './guestMeetings.js';

test('guest access is isolated, persisted, revoked and expires; closed links cannot reopen', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan-guest-store-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  let time = Date.parse('2026-10-02T15:00:00Z');
  const options = { filePath: path.join(root, 'meetings.json'), now: () => time };
  const store = createGuestMeetingStore(options);
  const host = { id: 'host', role: 'teacher', name: 'Иван' };
  const meeting = store.create(host, 'Пробное занятие');
  assert.equal(parseMeetingRoomId(meetingRoomId(meeting.id)).meetingId, meeting.id);
  assert.equal(parseMeetingRoomId('rtc:host:student'), null);
  assert.equal(meeting.maxParticipants, 20);
  assert.equal(Object.hasOwn(meeting, 'teacherId'), false);
  const guest = store.join(meeting.id, { name: '  Александр  ' });
  assert.equal(guest.user.name, 'Александр');
  assert.equal(fs.readFileSync(options.filePath, 'utf8').includes(guest.token), false);
  assert.deepEqual(createGuestMeetingStore(options).resolveToken(guest.token), guest.user);
  assert.equal(store.accessError(guest.user, meeting.id), '');
  const other = store.create(host, 'Другая встреча');
  assert.notEqual(store.accessError(guest.user, other.id), '');
  assert.notEqual(store.accessError({ ...host, id: 'outsider' }, meeting.id), '');
  assert.throws(() => store.control(meeting.id, 'outsider', 'close'), { status: 403 });
  store.control(meeting.id, host.id, 'lock');
  assert.throws(() => store.join(meeting.id, { name: 'Другой гость' }), { status: 403 });
  assert.equal(store.join(meeting.id, { resumeToken: guest.token }).user.id, guest.user.id);
  store.control(meeting.id, host.id, 'remove', guest.user.id);
  assert.equal(store.resolveToken(guest.token), null);
  assert.throws(() => store.join(meeting.id, { resumeToken: guest.token }), { status: 403 });
  store.control(meeting.id, host.id, 'unlock');
  const fresh = store.join(meeting.id, { name: 'Гость' });
  store.control(meeting.id, host.id, 'close');
  assert.equal(store.resolveToken(fresh.token), null);
  assert.throws(() => store.control(meeting.id, host.id, 'unlock'), { status: 410 });
  assert.throws(() => store.join(meeting.id, { name: 'Гость' }), { status: 410 });
  const secondGuest = store.join(other.id, { name: 'Гость' });
  time += 24 * 60 * 60 * 1000;
  assert.equal(store.resolveToken(secondGuest.token), null);
  assert.throws(() => store.get(other.id), { status: 410 });
});

test('blank names and too many open meetings are rejected without creating data', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan-guest-limits-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const store = createGuestMeetingStore({ filePath: path.join(root, 'meetings.json') });
  const host = { id: 'host', name: 'Иван' };
  const meeting = store.create(host);
  assert.throws(() => store.join(meeting.id, { name: ' \n ' }), { status: 400 });
  assert.throws(() => store.join(meeting.id, { resumeToken: 'invalid' }), { status: 403 });
  for (let i = 1; i < 10; i++) store.create(host);
  assert.throws(() => store.create(host), { status: 409 });
  store.control(meeting.id, host.id, 'close');
  assert.ok(store.create(host).open);
});
