import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createGuestMeetingStore, parseMeetingRoomId, meetingRoomId } from './guestMeetings.js';

test('guest access is isolated, persisted, revoked and expires; closed links cannot reopen', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan-guest-store-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  let time = Date.parse('2026-10-02T15:00:00Z');
  const options = { filePath: path.join(root, 'meetings.json'), now: () => time };
  const store = createGuestMeetingStore(options);
  const host = { id: 'host', role: 'teacher', name: 'Иван' };
  const meeting = store.create(host, 'Пробное занятие');
  assert.equal(parseMeetingRoomId(meetingRoomId(meeting.id)).meetingId, meeting.id);
  assert.equal(parseMeetingRoomId('rtc:host:student'), null);
  assert.equal(meeting.maxParticipants, 20);
  assert.equal(Object.hasOwn(meeting, 'teacherId'), false);
  const guest = store.join(meeting.id, { name: '  Александр  ' });
  assert.equal(guest.user.name, 'Александр');
  assert.equal(fs.readFileSync(options.filePath, 'utf8').includes(guest.token), false);
  assert.deepEqual(createGuestMeetingStore(options).resolveToken(guest.token), guest.user);
  assert.equal(store.accessError(guest.user, meeting.id), '');
  const other = store.create(host, 'Другая встреча');
  assert.notEqual(store.accessError(guest.user, other.id), '');
  assert.notEqual(store.accessError({ ...host, id: 'outsider' }, meeting.id), '');
  assert.throws(() => store.control(meeting.id, 'outsider', 'close'), { status: 403 });
  store.control(meeting.id, host.id, 'lock');
  assert.throws(() => store.join(meeting.id, { name: 'Другой гость' }), { status: 403 });
  assert.equal(store.join(meeting.id, { resumeToken: guest.token }).user.id, guest.user.id);
  store.control(meeting.id, host.id, 'remove', guest.user.id);
  assert.equal(store.resolveToken(guest.token), null);
  assert.throws(() => store.join(meeting.id, { resumeToken: guest.token }), { status: 403 });
  store.control(meeting.id, host.id, 'unlock');
  const fresh = store.join(meeting.id, { name: 'Гость' });
  store.control(meeting.id, host.id, 'close');
  assert.equal(store.resolveToken(fresh.token), null);
  assert.throws(() => store.control(meeting.id, host.id, 'unlock'), { status: 410 });
  assert.throws(() => store.join(meeting.id, { name: 'Гость' }), { status: 410 });
  const secondGuest = store.join(other.id, { name: 'Гость' });
  time += 24 * 60 * 60 * 1000;
  assert.equal(store.resolveToken(secondGuest.token), null);
  assert.throws(() => store.get(other.id), { status: 410 });
});

test('blank names and too many open meetings are rejected without creating data', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan-guest-limits-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const store = createGuestMeetingStore({ filePath: path.join(root, 'meetings.json') });
  const host = { id: 'host', name: 'Иван' };
  const meeting = store.create(host);
  assert.throws(() => store.join(meeting.id, { name: ' \n ' }), { status: 400 });
  assert.throws(() => store.join(meeting.id, { resumeToken: 'invalid' }), { status: 403 });
  for (let i = 1; i < 10; i++) store.create(host);
  assert.throws(() => store.create(host), { status: 409 });
  store.control(meeting.id, host.id, 'close');
  assert.ok(store.create(host).open);
});

test('public hosts have persisted control for one room only; invitations never expose host access', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan-public-host-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  let time = Date.parse('2026-10-02T15:00:00Z');
  const options = { filePath: path.join(root, 'meetings.json'), now: () => time };
  const store = createGuestMeetingStore(options);
  const host = store.createPublic({ name: '  Маша  ', title: 'Друзья' }, 'network-a');
  assert.equal(host.user.role, 'meeting-host');
  assert.equal(host.user.name, 'Маша');
  assert.equal(host.meeting.hostType, 'public');
  const info = store.get(host.meeting.id);
  for (const key of ['token', 'tokenHash', 'hostId', 'sourceKey', 'teacherId']) assert.equal(Object.hasOwn(info, key), false);
  const saved = fs.readFileSync(options.filePath, 'utf8');
  assert.equal(saved.includes(host.token), false);
  assert.equal(saved.includes('network-a'), false);
  const restarted = createGuestMeetingStore(options);
  assert.deepEqual(restarted.resolveToken(host.token), host.user);
  assert.equal(store.accessError(host.user, host.meeting.id), '');
  const otherHost = store.createPublic({ name: 'Миша' }, 'network-b');
  const guest = store.join(host.meeting.id, { name: 'Даша', role: 'meeting-host', hostId: host.user.id });
  assert.equal(guest.user.role, 'guest');
  assert.notEqual(store.accessError({ ...guest.user, role: 'meeting-host' }, host.meeting.id), '');
  assert.throws(() => store.controlPublic(host.meeting.id, guest.token, 'close'), { status: 403 });
  assert.throws(() => store.controlPublic(host.meeting.id, otherHost.token, 'close'), { status: 403 });
  assert.throws(() => store.control(host.meeting.id, host.user.id, 'close'), { status: 403 });
  assert.throws(() => store.join(otherHost.meeting.id, { resumeToken: host.token }), { status: 403 });
  assert.equal(store.controlPublic(host.meeting.id, host.token, 'lock').locked, true);
  assert.equal(store.join(host.meeting.id, { resumeToken: host.token }).user.id, host.user.id);
  assert.equal(store.join(host.meeting.id, { resumeToken: guest.token }).user.id, guest.user.id);
  assert.throws(() => store.join(host.meeting.id, { name: 'Новый' }), { status: 403 });
  assert.throws(() => store.controlPublic(host.meeting.id, host.token, 'remove', host.user.id), { status: 404 });
  store.controlPublic(host.meeting.id, host.token, 'remove', guest.user.id);
  assert.equal(store.resolveToken(guest.token), null);
  store.controlPublic(host.meeting.id, host.token, 'close');
  assert.equal(store.resolveToken(host.token), null);
  assert.throws(() => store.controlPublic(host.meeting.id, host.token, 'unlock'), { status: 410 });
  time += 24 * 60 * 60 * 1000;
  assert.equal(store.resolveToken(otherHost.token), null);
});

test('public room creation is bounded and can be disabled without stopping existing teacher meetings', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan-public-limits-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const filePath = path.join(root, 'meetings.json');
  const store = createGuestMeetingStore({ filePath, maxPublicMeetings: 4 });
  assert.throws(() => store.createPublic({ name: '\n ' }, 'ip'), { status: 400 });
  const host = store.createPublic({ name: 'Хозяин' }, 'ip');
  for (let i = 0; i < 2; i++) store.createPublic({ name: 'Другой' }, 'ip');
  assert.throws(() => store.createPublic({ name: 'Лишний' }, 'ip'), { status: 429 });
  store.createPublic({ name: 'Другой' }, 'other-ip');
  assert.throws(() => store.createPublic({ name: 'Ещё' }, 'third-ip'), { status: 503 });
  store.controlPublic(host.meeting.id, host.token, 'close');
  assert.ok(store.createPublic({ name: 'Новый' }, 'ip'));
  const disabled = createGuestMeetingStore({ filePath, publicEnabled: false });
  assert.equal(disabled.publicConfig().enabled, false);
  assert.throws(() => disabled.createPublic({ name: 'Гость' }), { status: 503 });
  const teacher = disabled.create({ id: 'teacher', name: 'Иван' });
  assert.ok(disabled.join(teacher.id, { name: 'Ученик' }));
});
