import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import WebSocket from 'ws';
import { subscriptionDay } from './learningSubscriptions.js';

test('real API preserves old finance, scopes purchases, gates live calls and downloads, and retains homework history', { timeout: 60_000 }, async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ivan-subscriptions-api-'));
  const dataDir = path.join(root, 'data'); const uploads = path.join(root, 'uploads');
  fs.mkdirSync(dataDir); fs.mkdirSync(uploads);
  const write = (name, value) => fs.writeFileSync(path.join(dataDir, `${name}.json`), JSON.stringify(value));
  const read = name => JSON.parse(fs.readFileSync(path.join(dataDir, `${name}.json`)));
  const now = new Date().toISOString(); const month = subscriptionDay(now).slice(0, 7);
  const hash = code => `scrypt$subscription-test$${crypto.scryptSync(code, 'subscription-test', 64).toString('base64')}`;
  write('teachers', ['a', 'b'].map(id => ({ id: `teacher-${id}`, name: id, codeHash: hash(`teacher-${id}-code`), createdAt: now })));
  write('students', ['old', 'recordings', 'foreign'].map(id => ({ id, teacherId: id === 'foreign' ? 'teacher-b' : 'teacher-a', name: id, code: `${id}-code`, grade: '11', createdAt: now })));
  const finance = { 'teacher-a': { studentProfiles: { old: { pricingMode: 'perLesson', lessonPrice: 2000 } }, months: { [month]: { students: { old: { paidAmount: 2000, lessonPrice: 2000 } } } } } };
  write('teacher-finances', finance);
  const group = { id: 'g2', teacherId: 'teacher-a', name: 'Группа 2', pricePerLesson: 900, status: 'active', startedAt: now, createdAt: now, updatedAt: now,
    members: ['old', 'recordings'].map(studentId => ({ studentId, status: 'active', joinedAt: now })) };
  write('learning-groups', [group]);
  const lessons = Array.from({ length: 16 }, (_, index) => ({ id: `lesson-${index + 1}`, groupId: 'g2', teacherId: 'teacher-a',
    startAt: new Date(Date.now() + (index + 1) * 3 * 86400_000).toISOString(), durationMinutes: 60, status: 'scheduled', participantIds: ['old', 'recordings'], createdAt: now, updatedAt: now }));
  write('learning-lesson-sessions', lessons);
  const assignment = { id: 'hw-group', groupId: 'g2', teacherId: 'teacher-a', title: 'Домашка', content: 'Решить задачу', recipientIds: ['old', 'recordings'], status: 'assigned', createdAt: now, publishedAt: now, updatedAt: now };
  write('learning-assignments', [assignment]);
  write('progress', { old: { progress: {}, schedule: [], homeworks: [{ id: 'individual-history', homeWork: 'История индивидуальной домашки', issuedAt: now }], solvedByTask: { 1: ['q1'] } } });
  write('tests', {});
  write('learning-materials', [{ id: 'material', groupId: 'g2', teacherId: 'teacher-a', title: 'Файл', kind: 'file', visibility: 'group', storageName: 'fixture.txt', originalName: 'fixture.txt', createdAt: now }]);
  fs.writeFileSync(path.join(uploads, 'fixture.txt'), 'fictional test material');
  const port = await new Promise(resolve => { const probe = net.createServer(); probe.listen(0, '127.0.0.1', () => { const value = probe.address().port; probe.close(() => resolve(value)); }); });
  const base = `http://127.0.0.1:${port}`; let logs = ''; const sockets = [];
  const startServer = () => {
    const processChild = spawn(process.execPath, ['server/index.js'], { cwd: path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'),
    env: { ...process.env, PORT: String(port), NODE_ENV: 'test', PLATFORM_DATA_DIR: dataDir, PLATFORM_UPLOADS_DIR: uploads, PLATFORM_JSON_BACKUPS_DIR: path.join(root, 'backups'), COLLAB_PERSISTENCE: '0', DISABLE_STARTUP_XP_REBALANCE: '1' }, stdio: ['ignore', 'pipe', 'pipe'] });
    processChild.stdout.on('data', chunk => { logs += chunk; }); processChild.stderr.on('data', chunk => { logs += chunk; });
    return processChild;
  };
  let child = startServer();
  t.after(async () => { sockets.forEach(ws => ws.terminate()); if (child.exitCode === null) { const exited = new Promise(resolve => child.once('exit', resolve)); child.kill(); await exited; } fs.rmSync(root, { recursive: true, force: true }); });
  const request = (url, token = '', method = 'GET', body) => fetch(`${base}${url}`, { method, headers: { Authorization: token ? `Bearer ${token}` : '', 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const json = async (response, status = 200) => { const data = await response.json(); assert.equal(response.status, status, JSON.stringify(data)); return data; };
  const join = (token, roomId) => new Promise((resolve, reject) => {
    const ws = new WebSocket(`ws://127.0.0.1:${port}/rtc?_auth=${encodeURIComponent(token)}`); sockets.push(ws);
    const timer = setTimeout(() => reject(new Error('Missing RTC response')), 5000);
    ws.once('open', () => ws.send(JSON.stringify({ type: 'join', roomId })));
    ws.once('error', reject); ws.on('message', raw => { const message = JSON.parse(String(raw)); if (['joined', 'error'].includes(message.type)) { clearTimeout(timer); resolve(message); } });
  });
  const waitForServer = async () => {
    const deadline = Date.now() + 20_000; let ready = false;
    while (Date.now() < deadline && child.exitCode === null) { try { if ((await request('/api/client-build-version')).ok) { ready = true; break; } } catch { /* server starting */ } await new Promise(resolve => setTimeout(resolve, 100)); }
    assert.ok(ready, logs);
  };
  await waitForServer();
  const login = async code => (await json(await request('/api/login', '', 'POST', { code }))).token;
  const teacher = await login('teacher-a-code'); const otherTeacher = await login('teacher-b-code');
  const old = await login('old-code'); const recordings = await login('recordings-code'); const foreign = await login('foreign-code');
  const baseRoute = '/api/learning-subscriptions';
  await json(await request(baseRoute), 401);
  const catalog = await json(await request(baseRoute, teacher));
  assert.equal(catalog.students.find(student => student.id === 'old').individualPrice, 2000);
  assert.equal(catalog.groups[0].pricePerLesson, 900); assert.equal(catalog.blocks.length, 0);
  assert.ok(!fs.existsSync(path.join(dataDir, 'learning-subscriptions.json')));
  assert.deepEqual(read('teacher-finances'), finance);
  const body = { studentId: 'old', groupId: 'g2', tariffId: 'group-main', startsAt: lessons[0].startAt, accessUntil: subscriptionDay(Date.parse(lessons[0].startAt) + 28 * 86400_000), keepCurrentPrice: true };
  await json(await request(baseRoute, old, 'POST', body), 403);
  await json(await request(baseRoute, otherTeacher, 'POST', body), 404);
  const created = await json(await request(baseRoute, teacher, 'POST', body), 201); const block = created.blocks[0];
  assert.equal(block.tariff.price, 7200);
  const markKey = `teacher-a:learning-group-session-lesson-1:${subscriptionDay(lessons[0].startAt)}:old:${new Date(lessons[0].startAt).toLocaleTimeString('ru-RU', { timeZone: 'Europe/Moscow', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' })}:paid`;
  await json(await request('/api/teacher-calendar-marks', teacher, 'PATCH', { set: { [markKey]: true } }), 409);
  await json(await request(`/api/learning-groups/g2/materials`, old), 402);
  await json(await request(`${baseRoute}/${block.id}/pay`, otherTeacher, 'POST', { amount: 7200 }), 404);
  await json(await request(`${baseRoute}/${block.id}/pay`, old, 'POST', { amount: 7200 }), 403);
  await json(await request(`${baseRoute}/${block.id}/pay`, teacher, 'POST', { amount: 900 }), 400);
  await json(await request(`${baseRoute}/${block.id}/pay`, teacher, 'POST', { amount: 7200 }));
  const savedPayment = read('learning-subscriptions').blocks[0].payment;
  await json(await request(`${baseRoute}/${block.id}/pay`, teacher, 'POST', { amount: 7200 }));
  assert.deepEqual(read('learning-subscriptions').blocks[0].payment, savedPayment);
  assert.deepEqual(read('teacher-finances'), finance, 'package payment is kept separately from legacy money');
  const own = await json(await request(baseRoute, old)); assert.equal(own.blocks.length, 1);
  assert.ok(!own.blocks[0].studentId && !own.blocks[0].teacherId && !own.blocks[0].payment.recordedBy);
  assert.equal((await json(await request(baseRoute, foreign))).blocks.length, 0);
  await json(await request(`${baseRoute}/${block.id}/renewal-request`, foreign, 'POST'), 404);
  await json(await request(`${baseRoute}/${block.id}/renewal-request`, old, 'POST'));
  await json(await request(`/api/learning-groups/g2/materials`, old));
  assert.equal((await request('/api/learning-materials/material/download', old)).status, 200);
  assert.equal((await request('/uploads/fixture.txt', old)).status, 200);
  const firstLesson = await json(await request('/api/learning-groups/g2/lessons/lesson-1', old));
  assert.equal(firstLesson.lesson.subscriptionAccess.live, true);
  assert.equal((await join(old, 'rtc:lesson:lesson-1')).type, 'joined', 'paid members can join a future lesson channel at any time');
  const recordPurchase = await json(await request(baseRoute, teacher, 'POST', { ...body, studentId: 'recordings', tariffId: 'recordings', keepCurrentPrice: false }), 201);
  const recordBlock = recordPurchase.blocks.find(entry => entry.studentId === 'recordings');
  await json(await request(`${baseRoute}/${recordBlock.id}/pay`, teacher, 'POST', { amount: 1900 }));
  assert.equal((await join(recordings, 'rtc:lesson:lesson-1')).type, 'error');
  const recordingLesson = await json(await request('/api/learning-groups/g2/lessons/lesson-1', recordings));
  assert.equal(recordingLesson.lesson.subscriptionAccess.live, false); assert.equal(recordingLesson.lesson.telemostUrl, '');
  await json(await request('/api/learning-groups/g2/lessons/lesson-8', teacher, 'PATCH', { startAt: new Date(Date.now() + 300).toISOString() }));
  assert.equal((await join(teacher, 'rtc:lesson:lesson-8')).type, 'joined');
  await new Promise(resolve => setTimeout(resolve, 1100));
  const conductedVoice = await json(await request('/api/learning-groups/g2/lessons/lesson-8', teacher));
  assert.equal(conductedVoice.lesson.status, 'active', 'teacher joining at lesson time starts a subscription lesson; early room preparation does not');
  const financial = await json(await request(`/api/teacher-finance?month=${month}`, teacher));
  const financialOld = financial.students.find(student => student.id === 'old');
  assert.equal(financialOld.profile.lessonPrice, 2000); assert.equal(financialOld.profitability.receivedRevenue, 9200);
  assert.equal(financialOld.record.paidAmount, 9200); assert.equal(financialOld.subscriptionPaidAmount, 7200);
  await json(await request('/api/student-next-lesson', old));
  const homeworksBefore = read('progress').old.homeworks;
  assert.ok(homeworksBefore.some(homework => homework.learningAssignmentId === assignment.id));
  assert.ok(homeworksBefore.some(homework => homework.id === 'individual-history'));
  sockets.forEach(ws => ws.terminate());
  const stopServer = async () => { const exited = new Promise(resolve => child.once('exit', resolve)); child.kill(); await exited; };
  await stopServer();
  const past = new Date(Date.now() - 3 * 86400_000).toISOString();
  write('learning-lesson-sessions', lessons.map((lesson, index) => index === 0 ? { ...lesson, startAt: past } : lesson));
  child = startServer(); await waitForServer();
  const missed = await json(await request('/api/learning-groups/g2/lessons', teacher));
  assert.equal(missed.lessons.find(lesson => lesson.id === 'lesson-1').status, 'cancelled', 'an unstarted scheduled lesson does not become a charged completed lesson');
  const stillFull = await json(await request(baseRoute, old));
  assert.equal(stillFull.blocks[0].remaining, 8);
  assert.ok(!stillFull.blocks[0].lessonIds.includes('lesson-1'));
  await stopServer();
  const all = read('learning-subscriptions'); all.blocks[0].accessUntil = '2026-01-01T00:00:00Z';
  write('learning-subscriptions', all);
  write('learning-lesson-sessions', lessons.map(lesson => all.blocks[0].lessonIds.includes(lesson.id) ? { ...lesson, status: 'completed', startAt: past, completedAt: past } : lesson));
  child = startServer(); await waitForServer();
  const expired = await json(await request(baseRoute, old)); assert.equal(expired.blocks[0].status, 'expired');
  assert.equal((await request('/api/learning-materials/material/download', old)).status, 404);
  assert.equal((await request('/uploads/fixture.txt', old)).status, 403);
  await json(await request('/api/session', old));
  await json(await request('/api/student-next-lesson', old));
  assert.ok(read('progress').old.homeworks.some(homework => homework.learningAssignmentId === assignment.id), 'expiry does not erase group homework');
  assert.ok(read('progress').old.homeworks.some(homework => homework.id === 'individual-history'), 'old individual history is retained');
  assert.equal(read('teacher-finances')['teacher-a'].studentProfiles.old.lessonPrice, 2000);
  assert.equal(read('learning-groups')[0].pricePerLesson, 900);
});
