export const PYTHON_RUNNER_SCRIPT = [
  'import ast',
  'import builtins as _builtins',
  'from base64 import b64decode',
  'import sys',
  'import traceback',
  'from io import StringIO as _StringIO',
  'from types import SimpleNamespace as _SimpleNamespace',
  'source = b64decode(sys.argv[1]).decode("utf-8", "replace")',
  'forbidden_names = {"__builtins__", "__import__", "open", "eval", "exec", "compile", "globals", "locals", "vars", "getattr", "setattr", "delattr", "breakpoint", "help"}',
  'forbidden_modules = {"os", "subprocess", "socket", "pathlib", "shutil", "ctypes", "inspect", "importlib", "pickle", "marshal"}',
  'forbidden_calls = {"__import__", "open", "eval", "exec", "compile", "globals", "locals", "vars", "getattr", "setattr", "delattr"}',
  'forbidden_nodes = (ast.With, ast.AsyncWith, ast.Raise, ast.Global, ast.Nonlocal, ast.ClassDef)',
  'tree = ast.parse(source, mode="exec")',
  'for node in ast.walk(tree):',
  '    if isinstance(node, ast.Import) and any(alias.name != "sys" for alias in node.names):',
  '        raise RuntimeError("Разрешён только импорт sys для чтения stdin")',
  '    if isinstance(node, ast.ImportFrom) and (node.module != "sys" or node.level or any(alias.name != "stdin" for alias in node.names)):',
  '        raise RuntimeError("Разрешён только from sys import stdin")',
  '    if isinstance(node, forbidden_nodes):',
  '        raise RuntimeError("Недопустимая конструкция Python")',
  '    if isinstance(node, ast.Name) and node.id in forbidden_names:',
  '        raise RuntimeError("Недопустимое имя в коде")',
  '    if isinstance(node, ast.Attribute) and node.attr.startswith("__"):',
  '        raise RuntimeError("Недопустимый доступ к атрибуту")',
  '    if isinstance(node, ast.alias) and node.name.split(".")[0] in forbidden_modules:',
  '        raise RuntimeError("Импорт модулей запрещен")',
  '    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in forbidden_calls:',
  '        raise RuntimeError("Недопустимый вызов функции")',
  'safe_builtin_names = {',
  '    "abs", "all", "any", "bin", "bool", "chr", "dict", "divmod", "enumerate", "filter", "float", "hex",',
  '    "int", "len", "list", "map", "max", "min", "oct", "ord", "pow", "print", "range", "reversed",',
  '    "round", "set", "sorted", "str", "sum", "tuple", "zip", "input", "EOFError", "iter", "next"',
  '}',
  'safe_builtins = {name: getattr(_builtins, name) for name in safe_builtin_names}',
  '# Expose only an in-memory stdin copy, never the real sys module or OS streams.',
  '_stdin = _StringIO(sys.stdin.read())',
  '_safe_sys = _SimpleNamespace(stdin=_stdin)',
  'def _safe_import(name, globals=None, locals=None, fromlist=(), level=0):',
  '    if name != "sys" or level or any(item != "stdin" for item in (fromlist or ())):',
  '        raise ImportError("Импорт модуля запрещён")',
  '    return _safe_sys',
  'def _safe_input(prompt=""):',
  '    if prompt:',
  '        print(prompt, end="")',
  '    line = _stdin.readline()',
  '    if line == "":',
  '        raise EOFError("EOF when reading a line")',
  '    return line[:-1] if line.endswith("\\n") else line',
  'safe_builtins["input"] = _safe_input',
  'safe_builtins["__import__"] = _safe_import',
  'globals_ns = {"__name__": "__main__", "__builtins__": safe_builtins}',
  'try:',
  '    exec(compile(tree, "<submitted>", "exec"), globals_ns, globals_ns)',
  'except Exception:',
  '    traceback.print_exc()',
  '    raise',
].join('\n');
