import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { moscowDay, addCalendarDays, weekdayIndex } from '../src/utils/groupAvailability.js';
import { expandRescheduleOccurrences } from './lessonReschedule.js';

test('full server: new pupil requests two weekly lessons, teacher approves, both calendars and future transfers see them after restart', {timeout:60000}, async t => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ivan-weekly-integration-'));const data=path.join(root,'data');fs.mkdirSync(data);
  const seed=(file,value)=>fs.writeFileSync(path.join(data,file),JSON.stringify(value));
  const createdAt=new Date().toISOString(), startDate=addCalendarDays(moscowDay(),2);
  seed('teachers.json',[{id:'t',name:'Teacher',code:'734001',createdAt},{id:'u',name:'Other',code:'734003',createdAt}]);
  seed('students.json',[{id:'a',teacherId:'t',name:'Анна',code:'734002',createdAt,deletedAt:null}]);
  seed('progress.json',{a:{schedule:[],homeworks:[],mockAttempts:{}}});seed('tests.json',{});seed('mock-exams.json',[]);
  const port=await new Promise(r=>{const s=net.createServer().listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p));});});
  let child,logs='';const stop=async()=>{if(!child||child.exitCode!==null)return;const done=new Promise(r=>child.once('exit',r));child.kill();await done;};
  t.after(async()=>{await stop();fs.rmSync(root,{recursive:true,force:true});});
  const boot=async()=>{child=spawn(process.execPath,['server/index.js'],{cwd:path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),env:{...process.env,NODE_ENV:'test',PORT:String(port),PLATFORM_DATA_DIR:data,PLATFORM_UPLOADS_DIR:path.join(root,'uploads'),PLATFORM_JSON_BACKUPS_DIR:path.join(root,'backups'),COLLAB_PERSISTENCE:'0',DISABLE_STARTUP_XP_REBALANCE:'1',LEARNING_GROUPS_ENABLED:'1'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',c=>logs+=c);child.stderr.on('data',c=>logs+=c);
    for(let i=0;i<180;i++){if(child.exitCode!==null)throw Error(logs);try{if((await fetch(`http://127.0.0.1:${port}/api/client-build-version`)).ok)return;}catch{/* Server is still starting. */}await new Promise(r=>setTimeout(r,100));}throw Error(logs);};
  const req=async(url,token='',body,status=200)=>{const r=await fetch(`http://127.0.0.1:${port}/api${url}`,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const v=await r.json();assert.equal(r.status,status,JSON.stringify(v)+'\n'+logs.slice(-500));return v;};
  await boot();const teacher=(await req('/login','',{code:'734001'})).token,student=(await req('/login','',{code:'734002'})).token,other=(await req('/login','',{code:'734003'})).token;
  await req('/weekly-schedules','',undefined,401);
  const availability=await req(`/weekly-schedules/availability?startDate=${startDate}`,student);
  const day=weekdayIndex(startDate),slots=[`${day}-600`,`${(day+2)%7}-600`];
  const row=await req('/weekly-schedules',student,{startDate,durationMinutes:60,slots,baseSignature:availability.baseSignature});
  assert.equal((await req('/student-schedule?studentId=a',student)).length,0);
  assert.equal((await req('/weekly-schedules',teacher)).requests[0].id,row.id);
  await req(`/weekly-schedules/${row.id}/approve`,other,{},403);
  assert.equal((await req(`/weekly-schedules/${row.id}/approve`,teacher,{})).status,'approved');
  const schedule=await req('/student-schedule?studentId=a',student);assert.equal(schedule.length,2);assert.ok(schedule.every(e=>e.repeatFrom===startDate&&!e.date));
  const calendar=await req('/teacher-schedule',teacher);assert.equal(calendar.filter(e=>e.studentId==='a').length,2);
  assert.equal(expandRescheduleOccurrences(calendar,addCalendarDays(startDate,364)).length,2);
  const move=await req('/lesson-reschedules/availability',student);assert.ok(move.lessons.some(e=>e.date===startDate&&e.time==='10:00'));
  await stop();await boot();await req(`/weekly-schedules/${row.id}/approve`,teacher,{});
  assert.equal((await req('/student-schedule?studentId=a',student)).length,2);
  assert.equal((await req('/weekly-schedules',student)).requests[0].status,'approved');
});
